### ISSUE TITLE
Hangman / Calculator

### ISSUE THREAD

**Issue by rufy545** [TheGoodDude22/AbigailBot#23]
Hello can you try to make a calculator and a hangman command with buttons? Something like this
![Screenshot_20220311-005526_Discord](https://user-images.githubusercontent.com/74645196/157775235-385d60b1-0edc-4b84-9d86-f3cbb54934d9.jpg)

**Comment by TheGoodDude22** [comment]
Hangman sounds like a great game to add! The calculator looks neat as well, I'll give it a shot!

**Comment by rufy545** [comment]
Ok nice
