### ISSUE TITLE
Getting a console error when using /play 

### ISSUE THREAD

**Issue by spencersablan** [TheGoodDude22/AbigailBot#8]
Everything works great with the bot until I tried using /play in discord.  Here is the error I am getting:

throw new Error(errorLog.join('\n'));
        ^

Error: Error: Cannot find module 'C:\Users\spenc\Personal Dev\AbigailBot\node_modules\@discordjs\opus\prebuild\node-v93-napi-v3-win32-x64-unknown-unknown\opus.node'
Require stack:
- C:\Users\spenc\Personal Dev\AbigailBot\node_modules\@discordjs\opus\lib\index.js
- C:\Users\spenc\Personal Dev\AbigailBot\node_modules\prism-media\src\util\loader.js
- C:\Users\spenc\Personal Dev\AbigailBot\node_modules\prism-media\src\opus\Opus.js
- C:\Users\spenc\Personal Dev\AbigailBot\node_modules\prism-media\src\opus\index.js
- C:\Users\spenc\Personal Dev\AbigailBot\node_modules\prism-media\src\index.js
- C:\Users\spenc\Personal Dev\AbigailBot\node_modules\discord-ytdl-core\index.js
- C:\Users\spenc\Personal Dev\AbigailBot\node_modules\discord-player\dist\Structures\Queue.js
- C:\Users\spenc\Personal Dev\AbigailBot\node_modules\discord-player\dist\Player.js
- C:\Users\spenc\Personal Dev\AbigailBot\node_modules\discord-player\dist\index.js
- C:\Users\spenc\Personal Dev\AbigailBot\index.js
Error: Cannot find module 'node-opus'
Require stack:
- C:\Users\spenc\Personal Dev\AbigailBot\node_modules\prism-media\src\util\loader.js
- C:\Users\spenc\Personal Dev\AbigailBot\node_modules\prism-media\src\opus\Opus.js
- C:\Users\spenc\Personal Dev\AbigailBot\node_modules\prism-media\src\opus\index.js
- C:\Users\spenc\Personal Dev\AbigailBot\node_modules\prism-media\src\index.js
- C:\Users\spenc\Personal Dev\AbigailBot\node_modules\discord-ytdl-core\index.js
- C:\Users\spenc\Personal Dev\AbigailBot\node_modules\discord-player\dist\Player.js
- C:\Users\spenc\Personal Dev\AbigailBot\node_modules\discord-player\dist\index.js
- C:\Users\spenc\Personal Dev\AbigailBot\index.js
Error: Cannot find module 'opusscript'
Require stack:
- C:\Users\spenc\Personal Dev\AbigailBot\node_modules\prism-media\src\util\loader.js
- C:\Users\spenc\Personal Dev\AbigailBot\node_modules\prism-media\src\opus\Opus.js
- C:\Users\spenc\Personal Dev\AbigailBot\node_modules\prism-media\src\opus\index.js
- C:\Users\spenc\Personal Dev\AbigailBot\node_modules\prism-media\src\index.js
- C:\Users\spenc\Personal Dev\AbigailBot\node_modules\discord-ytdl-core\index.js
- C:\Users\spenc\Personal Dev\AbigailBot\node_modules\discord-player\dist\Structures\Queue.js
- C:\Users\spenc\Personal Dev\AbigailBot\node_modules\discord-player\dist\Player.js
- C:\Users\spenc\Personal Dev\AbigailBot\node_modules\discord-player\dist\index.js
- C:\Users\spenc\Personal Dev\AbigailBot\index.js
    at Object.loader [as require] (C:\Users\spenc\Personal Dev\AbigailBot\node_modules\prism-media\src\util\loader.js:12:9)
    at loadOpus (C:\Users\spenc\Personal Dev\AbigailBot\node_modules\prism-media\src\opus\Opus.js:17:17)
    at new OpusStream (C:\Users\spenc\Personal Dev\AbigailBot\node_modules\prism-media\src\opus\Opus.js:46:10)
    at new Encoder (C:\Users\spenc\Personal Dev\AbigailBot\node_modules\prism-media\src\opus\Opus.js:149:5)
    at Object.transformer (C:\Users\spenc\Personal Dev\AbigailBot\node_modules\@discordjs\voice\dist\audio\TransformerGraph.js:120:24)
    at C:\Users\spenc\Personal Dev\AbigailBot\node_modules\@discordjs\voice\dist\audio\AudioResource.js:156:60
    at Array.map (<anonymous>)
    at Object.createAudioResource (C:\Users\spenc\Personal Dev\AbigailBot\node_modules\@discordjs\voice\dist\audio\AudioResource.js:156:41)
    at StreamDispatcher.createStream (C:\Users\spenc\Personal Dev\AbigailBot\node_modules\discord-player\dist\VoiceInterface\StreamDispatcher.js:108:38)
    at Queue.<anonymous> (C:\Users\spenc\Personal Dev\AbigailBot\node_modules\discord-player\dist\Structures\Queue.js:666:46)

**Comment by spencersablan** [comment]
The fix to this was to delete the @discordjs folder in the node_modules folder & then running this in the console:

`npm i @discordjs/node-pre-gyp node-addon-api @discordjs/opus`

I am on a new windows computer so that could have been the issue... but if anyone else is having this problem, then maybe we can create a more permanent solution to it.  Otherwise, we can close this issue.

**Comment by TheGoodDude22** [comment]
I'm going to try and do a fresh install of the bot and see if I get the same thing. I run the bot from the working repo files so I may miss some install isues.

**Comment by TheGoodDude22** [comment]
Mine is working correctly. I don't have a fresh system or VM to test on, so I'll close the issue unless this becomes common.
